version: '3.7'

services:
  frontend:
    mem_limit: 128m
    cpus: 0.2
    restart: unless-stopped
    image: asuzas/docker-m347-frontend
    container_name: docker-m347-frontend
    env_file: .env
    depends_on:
      - backend
    ports:
      - 3000:80

  backend:
    mem_limit: 512M
    cpus: 0.35
    restart: unless-stopped.
    image: asuzas/docker-m347-backend
    container_name: docker-m347-backend
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    mem_limit: 128m
    cpus: 0.05
    restart: unless-stopped
    image: 'postgres:10-alpine'
    container_name: db_m347_Bollin
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'