version: '3.7'

services:
  frontend:
    restart: always
    image: asuzas/docker-m347-frontend:v0.0.4
    container_name: docker-m347-frontend
    env_file: .env
    depends_on:
      - backend
    ports:
      - 8000:80
      - 8001:443
  backend:
    restart: always
    image: asuzas/docker-m347-backend:v0.0.4
    container_name: docker-m347-backend
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    restart: always
    image: 'postgres:10-alpine'
    container_name: db_m347_Bollin
    expose:
    - 5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'