name: CICD-restart

on: 
  workflow_run:
    workflows: ["CICD-Frontend", "CICD-Backend"]
    branches: [main]
    types: 
      - completed

jobs:
  restart-server-docker:
    name: Restart server docker compose
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3

      - name: copying remote shell script using password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: ./docker-compose.yml
          target: .

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker pull asuzas/docker-m347-backend
            docker pull asuzas/docker-m347-frontend
            docker-compose up -d